### ISSUE TITLE
zfs error makes system not bootable

### ISSUE THREAD

**Issue by dtd41** [BastilleBSD/bastille#563] opened 2022-12-22 21:18 UTC
OS is FreeBSD 12.3. I installed the latest version with pkg. Set the prefix to zroot and enable zfs. After bootstrap to download 12.3 and some false start creating and destroying containers, I did a create and started the console. checking zfs status with 'zfs list' there was no /zroot/bastille. /zoot/ROOT was added but zfs showed no datasets. Thinking a reboot was required I did that. The UEFI boot record was overwritten or deleted so the system was not bootable. This required a new install to correct.

Because I do not use pf, I did not configure it. Otherwise I followed the install process. I will install a new OS and see if I can duplicate this. A pretty bad bug from a user mistake, i.e., no pf.

**Comment by bmac2** [comment] 2023-10-19 02:17
@dtd41 were you able to recreate this??  Is this still an issue??  no one else reported a similar issue so please let me know the status.

**Comment by bmac2** [comment] 2023-10-21 23:28
NO steps to reproduce and no confirmation this is an issue.  Closing pending further information.

**Closed by bmac2** 2023-10-21 23:28 UTC
Labels: bug

**Comment by dtd41** [comment] 2023-10-22 13:21
Fine with me. My original submission described the steps. Answering a question wrong rendered PC. unbootable on freebsd 12.2. I am apparently the only one affected. I certainly will never try bastille again..On Oct 21, 2023, at 7:29 PM, Barry McCormick ***@***.***> wrote:﻿
Closed #563 as completed.

— Douglas ***@***.***: 301-217-9220 Fax: 301-217-9277Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.by  produ Message ID: ***@***.***>

**Comment by bmac2** [comment] 2023-10-22 19:26
@cedwards do we  need to investigate this one further??  I can't reproduce, nor has anyone else reported this.

**Comment by dtd41** [comment] 2023-10-23 12:00
No further action needed for me. I thought my post to the FreeBSD group was pretty clear on that. I appreciate your asking._____Douglas ***@***.***: 301-217-9220 Fax: 301-217-9277On Oct 22, 2023, at 3:27 PM, Barry McCormick ***@***.***> wrote:﻿
@cedwards do we  need to investigate this one further??  I can't reproduce, nor has anyone else reported this.
