### ISSUE TITLE
Limits not working ?

### ISSUE THREAD

**Issue by amarc** [BastilleBSD/bastille#541] opened 2022-08-26 23:42 UTC
Hello,

this is my initial journey with bastille, so this might be "RTFM" moment but I have to admit I have not found a lot in docs regarding limits.

So basically I added:

`kern.racct.enable="1"
`
in /boot/loader.conf

than I simply tried something like:

`bastille limits nginx3 memoryuse 4G
`

but limits are not aplied at all. Also on stop/start of jail I can see errors like:

```
rctl: failed to remove rule 'jail:nginx3:cpu:deny=1/jail': Invalid argument
rctl: failed to remove rule 'jail:nginx3:cpu:log=1/jail': Invalid argument
rctl: failed to remove rule 'jail:nginx3:cpuuse:deny=1/jail': Invalid argument
rctl: failed to remove rule 'jail:nginx3:cpuuse:log=1/jail': Invalid argument
```

This is on 13.1 FreeBSD and   bastille 0.9.20220714

So what am I missing here and how can I fix it ?

ty.

**Comment by bsdlme** [comment] 2023-03-16 20:30
I can't reproduce this on 13.2-RC1 and bastille-0.9.20220714.

Maybe you did not reboot after editring `/boot/loader.conf`?

```
$ doas bastille limits niceproxy memoryuse 1G
[niceproxy]:
memoryuse 1G

$ doas rctl
jail:niceproxy:memoryuse:log=1073741824
jail:niceproxy:memoryuse:deny=1073741824
```

**Comment by bmac2** [comment] 2023-10-18 18:45
seems question is answered.  Closing issue.

**Closed by bmac2** 2023-10-18 18:45 UTC
