### ISSUE TITLE
[BUG] bastille lists running iocage jails

### ISSUE THREAD

**Issue by jemail99** [BastilleBSD/bastille#325] opened 2021-01-24 17:31 UTC
**[MANDATORY] Describe the bug [MANDATORY]**
iocage installed and an iocage jail serviio created.
bastille installed and bootstrapped with freebsd 12.2-RELEASE. No bastille jails created.
bastille lists running iocage jails.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-RELEASE-p1
12.2-RELEASE-p1
12.2-RELEASE-p2

**[MANDATORY] How did you install bastille? (port/pkg/git)**
installed via pkg

**[optional] Steps to reproduce?**
`  bastllie list`
`  JID                IP Address       Hostname   Path`
`  ioc-serviio     192.168.1.32   *.*.*            /zroot/iocage/jails/serviio/root`

**[optional] Expected behavior**
bastille should only list bastille jails.

**[optional]  Additional context**
I have not tried to run other bastille commands using the iocage jail serviio as a TARGET as this could be dangerous and I don't want to take the chance of causing problems with my iocage serviio jail instance.

**Comment by xaque208** [comment] 2021-01-24 17:44
`| grep -v 'ioc-'` maybe.

**Comment by jemail99** [comment] 2021-01-24 18:16
Yes your suggestion will work.
Perhaps this is more a feature than a bug.
However iocage list only lists iocage jails and I think bastille should do the same to avoid confusion.

**Comment by hackacad** [comment] 2021-01-24 18:37
Grepping for ioc-* is not valid solution.

The intersection of `jls` and `${bastille_jailsdir}/${_JAIL}` would give you the correct results. I'd agree that this is not a bug, as `bastille list` shows all running jails. You can show all available  Bastille jails with `bastille list jails`.

IMHO: I wouldn't run both iocage and bastille on the same system. Both use the same base command and I'm not sure if they could interfere at other points well.

**Comment by jpoa** [comment] 2021-02-16 18:00
I am using CBSD for jail management and Bastille for templating (very happily I must add), so for me this is a feature not a bug.

Now since the update of 2021 this is not working. Bastille list will show the jails but bastille template will not work (complains it cannot find the jail).

Any chance we can go back to the previous behavior? This is really unfortunate to me.

(And yes, been using cbsd and bastille for around a year with great results)

**Comment by bmac2** [comment] 2023-10-19 15:55
This works as designed and is a feature, not a bug.  Closing issue as will not fix.

**Closed by bmac2** 2023-10-19 15:55 UTC
Labels: bug
