### ISSUE TITLE
[BUG] "bastille rename" does not update fstab content for Linux container

### ISSUE THREAD

**Issue by tofazzz** [BastilleBSD/bastille#487] opened 2022-01-16 16:54 UTC
- Bug: When renaming a Linux jail with "bastille rename "target" "new name" the command misses to update the paths located in the fstab file for the jail. If I manually update the paths in the file the jail starts fine.

- Bastille and FreeBSD version:
0.9.20211225
13.0-RELEASE-p6

- Bastille installed via pkg

- Steps:
1. Create Linux jail and make sure it runs fine
2. Stop the jail
3. Rename the jail with a new name
4. Start the jail and the following error is shown:
"mount: /usr/local/bastille/jails/"old jail name": No such file or directory
jail: "new jail name": /sbin/mount -t devfs -o rw devfs /usr/local/bastille/jails/"old jail name"/root/dev: failed

- Fix: The command should update the fstab file as well with the new jail name in all mount points

**Comment by JRGTH** [comment] 2022-01-16 18:03
Hello thanks for report.

This should fix the issue: https://github.com/BastilleBSD/bastille/pull/488

**Comment by tofazzz** [comment] 2022-01-16 19:42
Thank you very much! :)

**Comment by bedwardly-down** [comment] 2022-01-19 23:40
I can confirm. It's not just a Linux jail but the normal ones too. I found that manually editing the fstab to reflect the new directory name can cause the jail to to start up and then never stop without a full server restart too. That probably should be a separate bug, too.

**Comment by JRGTH** [comment] 2022-01-20 10:49
> I can confirm. It's not just a Linux jail issue but for normal ones too. I found that manually editing the fstab to reflect the new directory name can sometimes cause the jail to to start up and then never stop without a full server restart too. That probably should be a separate bug, too.
> 
> EDIT: My bug was related to [this](https://github.com/go-gitea/gitea/issues/18180) and not Bastille-centric. Carry on

Hi, yes you are correct, manually editing not only `fstab` but also `jail.conf` while container running is never advisable as anything who changes a path may cause jail start/stop issues as expected.

Also the rename command will take care of the `bastille` related entries and the user need to update for customs, this is why the `bastille rename` requires the jail to be stopped on the first place.

Regards

**Comment by zilti** [comment] 2022-08-26 15:47
Since the fix for this got merged, it'd be good to close this issue.

**Closed** 2022-08-26 16:27 UTC
Labels: bug
