### ISSUE TITLE
[BUG] pfctl still invoked on VNET jails

### ISSUE THREAD

**Issue by michael-o** [BastilleBSD/bastille#346] opened 2021-02-15 14:51 UTC
**[MANDATORY] Describe the bug [MANDATORY]**
I have a vnet jail, no loopback `bastille0` yet I see on stop:
```
# bastille restart deblndw013x1j
pfctl: /dev/pf: No such file or directory
rdr-anchor not found in pf.conf
[deblndw013x1j]:
deblndw013x1j: removed
```
I don't have pf enabled and don't need it on the jailhost.

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.8.20210115
12.2-STABLE
12.2-STABLE
12.2-STABLE

**[MANDATORY] How did you install bastille? (port/pkg/git)**
port

**[optional] Steps to reproduce?**
Create a vnet jail, start and stop

**[optional] Expected behavior**
No `pfctl` actions

**[optional]  Additional context**
The issue comes from here: https://github.com/BastilleBSD/bastille/blob/af8d766b0e3b8f93ba360e9996bfb0457feb7174/usr/local/share/bastille/stop.sh#L59-L60

My understanding ist that pf is only necessary when you don't have external external IP addresses and need to do NAT. This does not apply to VNET jails. I do run VNET only. I don't know whether `bastille rdr ...` can also be run at runtime, but all rdr/pdf/loopback related checks should be skipped for a VNET jail.

**Comment by KizzyCode** [comment] 2021-02-16 18:19
That depends; for example I have a VNET setup which is NATed to my external interface so that I can access the internet or deploy a VPN server inside a jail.

So in my case it's a good thing that Bastille behaves this way, however there should be a way to configure this depending on your setup I guess.

**Comment by michael-o** [comment] 2021-02-16 19:23
> That depends; for example I have a VNET setup which is NATed to my external interface so that I can access the internet or deploy a VPN server inside a jail.

What is the purpose of having VNET jails when you do NAT where you could just use cloned `lo1`? Isn't the whole point being not dependent of the host's interface?

> So in my case it's a good thing that Bastille behaves this way, however there should be a way to configure this depending on your setup I guess.
Maybe for you, but this is an assumption Bastille does w/o knowning this jail uses pf anyhow. It should be configure whether bastille should interact with pf.

**Comment by KizzyCode** [comment] 2021-02-16 20:49
> What is the purpose of having VNET jails when you do NAT where you could just use cloned `lo1`? Isn't the whole point being not dependent of the host's interface?

Some applications require a dedicated network stack and do not work with `lo`; e.g. WireGuard or some firewall applications. Therefore you need to create a VNET that is bridged to your external interface for inet connectivity. And because you usually have only one IPv4 address, you need NAT and RDR.

**Comment by michael-o** [comment] 2021-02-16 21:34
@KizzyCode I'd be interested how this looks like configuration-wise.

**Comment by KizzyCode** [comment] 2021-02-16 21:47
Ok, basically:
1. You create a bridge device; e.g. `em0bridge` and add your external interface `em0` to it
2. You assign an IP to your bridge that serves as gateway; e.g. `10.0.1.1/24`
3. You create an `epair` pair; e.g. `vnet0_host` and `vnet0_jail` (bastille does that automatically)
4. You add `vnet0_host` to `em0bridge` (bastille does that automatically)
5. You add `vnet0_jail` to the jail and assign a subnet compatible address; e.g. `10.0.1.10/24` (bastille does that automatically)
6. You add your bridge's address `10.0.1.1` as default route to the jail

So thats the point where we need NAT for outgoing traffic and RDR for incoming traffic. Currently I use `nat on em0 from em0bridge:network to any -> em0`; the redirects are configured via `pf` (using `rdr-anchor "rdr/*"` in the config).

For a more complete example, take a look at: https://genneko.github.io/playing-with-bsd/networking/freebsd-wireguard-jail/

**Comment by michael-o** [comment] 2021-06-13 11:35
While I see -- after @KizzyCode's explanation -- use cases for this, this should be create time option whether bastiile should take care of this or not.

**Comment by michael-o** [comment] 2021-07-14 10:16
Can this finally be solved by provinding a `--pf` or something similar to the `bastille create` command`? Bastille can merorize it and call pf only if the jail has been created with the option.

**Comment by JRGTH** [comment] 2021-07-14 11:17
I don't use `pf` and I have a similar jail stop issue here, however I'm not sure but I think this PR: 211a268c36ecad5db055f260e43ce6133748513c solves the stop `pf` invocation issue, as well as for embedded system only using IPFW or not having `pf` command at all.

Regards

**Comment by michael-o** [comment] 2022-11-08 21:08
Can this finally be addressed?

**Comment by michael-o** [comment] 2023-12-21 10:59
This is still open in the latest relese :-(

**Comment by tschettervictor** [comment] 2024-12-10 18:20
Is this still an issue?
I'm trying to reproduce it, but can't.
@michael-o

**Comment by michael-o** [comment] 2024-12-10 20:22
> Is this still an issue? I'm trying to reproduce it, but can't. @michael-o
> 
> The start and stop commands will only invoke pfctl if the command itself is found, or the "ip4.addr" is set in jail.conf

The command is always present:
```
root@deblndw013x:~
# which pfctl
/sbin/pfctl
root@deblndw013x:~
# service pf status
pf.ko is not loaded
```
thus
```
root@deblndw013x:~
# bastille restart deblndw013x2j
pfctl: /dev/pf: No such file or directory
rdr-anchor not found in pf.conf
[deblndw013x2j]:
deblndw013x2j: removed

pfctl: /dev/pf: No such file or directory
[deblndw013x2j]:
e0a_bastille3
e0b_bastille3
deblndw013x2j: created
```
with
```
root@deblndw013x:~
# bastille version
0.12.20241124
```

**Comment by tschettervictor** [comment] 2024-12-10 20:31
Can you try adding "> /dev/null" to the "which -s pfctl" command?

**Comment by michael-o** [comment] 2024-12-10 20:36
```
root@deblndw013x:~
# which -s pfctl ; echo $?
0
```

**Comment by tschettervictor** [comment] 2024-12-10 20:37
I mean inside the "stop.sh" script.

**Comment by michael-o** [comment] 2024-12-10 20:47
> I mean inside the "stop.sh" script.

Seems to be inconsistent this check:
```
root@deblndw013x:/usr/local/share/bastille
# grep  pfctl start.sh stop.sh
start.sh:            pfctl -q -t "${bastille_network_pf_table}" -T add "${ip}"
stop.sh:        # Check if pfctl is present
stop.sh:        if which -s pfctl; then
stop.sh:                pfctl -q -t "${bastille_network_pf_table}" -T delete "${_ip}"
```
but does one expect the system to be compiled without pf? The test with `which` does not indicate that pdf is actually running...

**Comment by michael-o** [comment] 2024-12-10 20:50
> This check should actually check if NAT is being used before attempting to call pfctl.

Obviously, it doesn't :-(

**Comment by michael-o** [comment] 2024-12-10 20:52
Here is the problem:
```
root@deblndw013x:/usr/local/share/bastille
# bastille config deblndw013x1j get ip4.addr
not set
```
but the test does:
```
 82         ip=$(bastille config "${_jail}" get ip4.addr)
 83         if [ -n "${ip}" ]; then
```
obviously `bastille config` is implemented incorrectly

**Comment by michael-o** [comment] 2024-12-10 20:58
The logic to determine the IPv4 addressed in start.sh is different to stop.sh. stop.sh needs to be aligned to start.sh and the issue should be gone.

**Comment by michael-o** [comment] 2024-12-10 20:59
Fix for start.sh:
```
if [ "${ip}" != 'not set' ]; then
```
Will need to raise a PR for this.

**Comment by tschettervictor** [comment] 2024-12-10 21:05
> Fix for start.sh:
> 
> ```
> 
> if [ "${ip}" != 'not set' ]; then
> 
> ```
> 
> Will need to raise a PR for this.

Does this function as expected?

**Comment by michael-o** [comment] 2024-12-10 21:18
> > Fix for start.sh:
> > ```
> > 
> > if [ "${ip}" != 'not set' ]; then
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Will need to raise a PR for this.
> 
> Does this function as expected?

Yes, pf is then skipped at start time.

**Comment by tschettervictor** [comment] 2024-12-10 21:19
Great! I'll open a PR.

**Comment by tschettervictor** [comment] 2024-12-10 21:41
For me the ip4.addr can also sometimes be "-" so I'll include that also.

**Comment by michael-o** [comment] 2024-12-10 21:46
> For me the ip4.addr can also sometimes be "-" so I'll include that also.

How so? Buy if so, search for other occurrences as well.

**Comment by tschettervictor** [comment] 2024-12-10 21:47
```
root@webmin:~ # jls -j jail2 ip4.addr
-
root@webmin:~ # jls -j jail2 ip6.ddr
-
```

**Comment by tschettervictor** [comment] 2024-12-10 21:53
#769

**Comment by bmac2** [comment] 2024-12-27 19:05
fixed with PR just merged

**Closed by bmac2** 2024-12-27 19:05 UTC
Labels: bug
