### ISSUE TITLE
[BUG] Reeboted Host, Jails Missing

### ISSUE THREAD

**Issue by gallexme** [BastilleBSD/bastille#228] opened 2020-07-22 17:36 UTC
**[MANDATORY] Describe the bug [MANDATORY]**
rebooted my system ,jail not runing checked:

```
sudo bastille start database
[database]:
database: created
jail: database: /bin/sh /etc/rc: failed
database: removed
  interface = bastille0;
jls: jail "database" not found
no IP address found for

```

**[MANDATORY] Bastille and FreeBSD version (paste ``bastille -v && freebsd-version -kru`` output)**
0.6.20200414
12.1-RELEASE-p7
12.1-RELEASE-p7
12.1-RELEASE-p7

**[MANDATORY] How did you install bastille? (port/pkg/git)**

pkg

**[optional] Expected behavior**
resillent to reboots

**[optional]  Additional context**
prolly fstab or so problem of the jail i dunno

```
database cat jail.conf
database {
  devfs_ruleset = 4;
  enforce_statfs = 2;
  exec.clean;
  exec.consolelog = /usr/local/bastille/logs/database_console.log;
  exec.start = '/bin/sh /etc/rc';
  exec.stop = '/bin/sh /etc/rc.shutdown';
  host.hostname = database;
  mount.devfs;
  mount.fstab = /usr/local/bastille/jails/database/fstab;
  path = /usr/local/bastille/jails/database/root;
  securelevel = 2;

  interface = bastille0;
  ip4.addr = 10.17.89.10;
  ip6 = disable;
}

```
```
 cat fstab
/usr/local/bastille/releases/12.1-RELEASE /usr/local/bastille/jails/database/root/.bastille nullfs ro 0 0

```

zfs list
```

zroot/ROOT                            2.39G  54.8G    88K  none
zroot/ROOT/default                    2.39G  54.8G  2.39G  /
zroot/bastille                        1.05G  54.8G    96K  /usr/local/bastille
zroot/bastille/backups                  88K  54.8G    88K  /usr/local/bastille/backups
zroot/bastille/cache                   297M  54.8G   143M  /usr/local/bastille/cache
zroot/bastille/cache/12.1-RELEASE      154M  54.8G   154M  /usr/local/bastille/cache/12.1-RELEASE
zroot/bastille/jails                   378M  54.8G    88K  /usr/local/bastille/jails
zroot/bastille/jails/database          378M  54.8G    92K  /usr/local/bastille/jails/database
zroot/bastille/jails/database/root     378M  54.8G   378M  /usr/local/bastille/jails/database/root
zroot/bastille/logs                     92K  54.8G    92K  /usr/local/bastille/logs
zroot/bastille/releases                402M  54.8G    88K  /usr/local/bastille/releases
zroot/bastille/releases/12.1-RELEASE   402M  54.8G   402M  /usr/local/bastille/releases/12.1-RELEASE
zroot/bastille/templates               312K  54.8G   312K  /usr/local/bastille/templates
zroot/tmp                               88K  54.8G    88K  /tmp
zroot/usr                             3.79G  54.8G    88K  /usr
zroot/usr/home                        3.10G  54.8G  3.10G  /usr/home
zroot/usr/ports                         88K  54.8G    88K  /usr/ports
zroot/usr/src                          704M  54.8G   704M  /usr/src
zroot/var                             2.56M  54.8G    88K  /var
zroot/var/audit                         88K  54.8G    88K  /var/audit
zroot/var/crash                         88K  54.8G    88K  /var/crash
zroot/var/log                         2.08M  54.8G  2.08M  /var/log
zroot/var/mail                         140K  54.8G   140K  /var/mail
zroot/var/tmp                           88K  54.8G    88K  /var/tmp

```

```
cat /usr/local/etc/bastille/bastille.conf
#####################
## [ BastilleBSD ] ##
#####################

## default paths
bastille_prefix=/usr/local/bastille                                   ## default: "/usr/local/bastille"
bastille_backupsdir=${bastille_prefix}/backups                        ## default: ${bastille_prefix}/backups
bastille_cachedir=${bastille_prefix}/cache                            ## default: ${bastille_prefix}/cache
bastille_jailsdir=${bastille_prefix}/jails                            ## default: ${bastille_prefix}/jails
bastille_logsdir=${bastille_prefix}/logs                              ## default: ${bastille_prefix}/logs
bastille_releasesdir=${bastille_prefix}/releases                      ## default: ${bastille_prefix}/releases
bastille_templatesdir=${bastille_prefix}/templates                    ## default: ${bastille_prefix}/templates

## bastille scripts directory (assumed by bastille pkg)
bastille_sharedir=/usr/local/share/bastille                           ## default: "/usr/local/share/bastille"

## bootstrap archives (base, lib32, ports, src, test)
bastille_bootstrap_archives="base"                                    ## default: "base"

## default timezone
bastille_tzdata="Etc/UTC"                                             ## default: "Etc/UTC"

## default jail resolv.conf
bastille_resolv_conf="/etc/resolv.conf"                               ## default: "/etc/resolv.conf"

## bootstrap urls
bastille_url_freebsd="http://ftp.freebsd.org/pub/FreeBSD/releases/"          ## default: "http://ftp.freebsd.org/pub/FreeBSD/releases/"
bastille_url_hardenedbsd="http://installer.hardenedbsd.org/pub/hardenedbsd/" ## default: "https://installer.hardenedbsd.org/pub/HardenedBSD/releases/"

## ZFS options
bastille_zfs_enable="YES"                                                ## default: ""
bastille_zfs_zpool="zroot"                                                 ## default: ""
bastille_zfs_prefix="bastille"                                        ## default: "${bastille_zfs_zpool}/bastille"
bastille_zfs_options="-o compress=lz4 -o atime=off"                   ## default: "-o compress=lz4 -o atime=off"

## Export/Import options
bastille_compress_xz_options="-0 -v"                                  ## default "-0 -v"
bastille_decompress_xz_options="-c -d -v"                             ## default "-c -d -v"

## Networking
bastille_network_loopback="bastille0"                                 ## default: "bastille0"
bastille_network_shared=""                                            ## default: ""
bastille_network_gateway=""                                           ## default: ""

```

**Comment by cedwards** [comment] 2020-07-22 17:45
That is unexpected behavior that I haven't seen before. Looping in @JRGTH .

**Comment by gallexme** [comment] 2020-07-22 17:49
for testing purposes i created a new jail
the fstab + jail.conf are equal..... but that one runs

**Comment by gallexme** [comment] 2020-07-22 17:54
here a comparison of both file structures, seemsl like /home is missing and bin etc...

left is the one which doenst work
![image](https://user-images.githubusercontent.com/1122989/88210908-30b9f080-cc55-11ea-8c9b-3a9efc758294.png)

right is the new one

**Comment by gallexme** [comment] 2020-07-22 17:56
oh right that could be cause fstab doesnt run n links .bastile/sbin etc

**Comment by gallexme** [comment] 2020-07-22 18:24
```sh
LINK_LIST="bin boot lib libexec rescue sbin usr/bin usr/include usr/lib usr/lib32 usr/libdata usr/libexec usr/sbin usr/share usr/src"
            for _link in ${LINK_LIST}; do
                ln -sf /.bastille/${_link} ${_link}
            done
```

i ran this in the root folder now it works again

anyone knows why the links got deleted?

**Comment by JRGTH** [comment] 2020-07-27 21:00
I could not reproduce this issue with either UFS or ZFS filesystems under FreeBSD 12.1-RELEASE-p7.

If this doesn't have something to do with the jails mountpoints, then looks like unexpected data lost or something a like which is really odd definitely, I wonder if this is still happening on your system/setup?

Regards

**Comment by gallexme** [comment] 2020-07-28 08:35
Maybe it was because i blindly followed the instructions?
I installed bastille, enabled it in sysrc, set up the zfs config, then
created that jail, without restarting bastille inbetween, then some time
later I rebooted, with the issue coming up

**Comment by bmac2** [comment] 2023-10-18 19:48
Could not reproduce.   @JRGTH @gallexme   closing this one.  IF it occurs again, please capture steps to reproduce and put in a BUG ticket for me to evaluate.

**Closed by bmac2** 2023-10-18 19:48 UTC
Labels: bug
