### ISSUE TITLE
[BUG] "bastille destroy <jailname>" cannot remove jail folder in ZFS 

### ISSUE THREAD

**Issue by tofazzz** [BastilleBSD/bastille#214] opened 2020-05-22 19:24 UTC
I tried to delete one of my Jails using the destroy command and I have received the following error:

`Deleting Jail: MAIL1.`
`cannot unmount '/usr/local/bastille/jails/MAIL1/root': Device busy`
`rm: /usr/local/bastille/jails/MAIL1/root: Device busy`
`rm: /usr/local/bastille/jails/MAIL1: Device busy`

All files were removed beside the folders /usr/local/bastille/jails/jailname/root and it looks like they are still mounted:

zroot/bastille/jails/MAIL1 on /usr/local/bastille/jails/MAIL1 (zfs, local, noatime, nfsv4acls)
zroot/bastille/jails/MAIL1/root on /usr/local/bastille/jails/MAIL1/root (zfs, local, noatime, nfsv4acls)

Bastille 0.6.20200412
FreeBSD 12.1-RELEASE-p5

Bastille installed via pkg and enabled ZFS with the options:

`bastille_zfs_enable="YES" `
`bastille_zfs_zpool="zroot" `

Workaround:
Rebooted the server and executed again "bastille destroy jailname" which its been successful and the folders are gone.

**Comment by JRGTH** [comment] 2020-05-23 01:18
This usually means that there was a file and/or shell still open, either checking for open shells and terminate them, `fstat` may help or just force unmount the jail mountpoint in question can do the trick.

**Here is an example for a locked bastille jail under ZFS:**

**Behavior:**
```
root@server: ~# bastille destroy locked
Deleting Jail: locked.
cannot unmount '/mnt/storage/bastille/jails/locked/root': Device busy
rm: /mnt/storage/bastille/jails/locked/root: Device busy
rm: /mnt/storage/bastille/jails/locked: Device busy
```

**Solution:**
```
root@server: ~# zfs umount -f /mnt/storage/bastille/jails/locked
root@server: ~# bastille destroy locked
Deleting Jail: locked.

root@nas-mserver: ~#
```

However I would recommend looking what is still open and/or in use under said jail.
Regards

**Comment by JRGTH** [comment] 2020-05-23 01:58
Since the jail files are deleted regardless as previously denoted, this issue may be addressed with the following PR: [Option to force destroy jail in ZFS](https://github.com/BastilleBSD/bastille/pull/215/commits/147e7d5db31157e48f9d1e20c135188c3aa9e07f)

Regards

**Comment by tofazzz** [comment] 2020-05-23 17:51
Thank you for the trick! I just assumed that the "destroy" command would have dealt with that without any further option as basically I am requesting to destroy/remove a Jail that is stopped.

**Comment by JRGTH** [comment] 2020-07-09 01:30
Thanks, since the issue is already fixed after adding `OPTIONS="-rf"`, closing here.
Regards

**Closed** 2020-07-09 01:31 UTC
Labels: bug
